version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/bookers2-api:/app
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "5555:5555"
    networks:
      - app-network

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front/bookers2-front:/app
    ports:
      - "4000:3000"
    networks:
      - app-network

  db:
    image: postgres:15.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pw
      POSTGRES_DB: test_db
    restart: always
    networks:
      - app-network

  web:
    image: nginx:1.21
    ports:
      - 80:80
    volumes:
      - ./nginx:/app
      - ./nginx/nginx.develop.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - api
      - front

networks:
  app-network:
    driver: bridge
