import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="shadow-md py-4 px-4 sm:px-10 bg-dark font-[sans-serif] min-h-[70px]">
          <div className="flex flex-wrap items-center justify-between gap-5 relative">
            <a>
              <img className="w-36" />
            </a>
            <div className="flex lg:order-1 max-sm:ml-auto">
              <Link href="log-in">
                <button className="px-4 py-2 text-sm rounded-full font-bold text-white bg-indigo-600 transition-all ease-in-out duration-300 hover:bg-transparent hover:text-indigo-600">
                  Login
                </button>
              </Link>
              <Link href="sign-up">
                <button className="px-4 py-2 text-sm rounded-full font-bold text-white bg-indigo-600 transition-all ease-in-out duration-300 hover:bg-transparent hover:text-[indigo-600] ml-3">
                  Sign up
                </button>
              </Link>
              <button id="toggle" className="lg:hidden ml-7">
                <svg
                  className="w-7 h-7"
                  fill="#000"
                  viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    fillRule="evenodd"
                    d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                    clipRule="evenodd"
                  ></path>
                </svg>
              </button>
            </div>
            <ul
              id="collapseMenu"
              className="lg:!flex lg:space-x-5 max-lg:space-y-2 max-lg:hidden max-lg:py-4 max-lg:w-full"
            >
              <li className="max-lg:border-b max-lg:bg-[#007bff] max-lg:py-2 px-3 max-lg:rounded">
                <a className="lg:hover:text-[#007bff] text-[#007bff] max-lg:text-white block font-semibold text-[15px]">
                  Home
                </a>
              </li>
              <li className="max-lg:border-b max-lg:py-2 px-3 max-lg:rounded">
                <a className="lg:hover:text-[#007bff] text-gray-500 block font-semibold text-[15px]">
                  Team
                </a>
              </li>
              <li className="max-lg:border-b max-lg:py-2 px-3 max-lg:rounded">
                <a className="lg:hover:text-[#007bff] text-gray-500 block font-semibold text-[15px]">
                  Feature
                </a>
              </li>
              <li className="max-lg:border-b max-lg:py-2 px-3 max-lg:rounded">
                <a className="lg:hover:text-[#007bff] text-gray-500 block font-semibold text-[15px]">
                  Blog
                </a>
              </li>
              <li className="max-lg:border-b max-lg:py-2 px-3 max-lg:rounded">
                <a className="lg:hover:text-[#007bff] text-gray-500 block font-semibold text-[15px]">
                  About
                </a>
              </li>
              <li className="max-lg:border-b max-lg:py-2 px-3 max-lg:rounded">
                <a>Contact</a>
              </li>
            </ul>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
